apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-image
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/tekton-pipelines/spring-petclinic
  type: image