# This workflow build, publish and deploy a java app to your OpenShift cluster
#
# To configure this workflow:
#
# 1. Setup secrets in your repository by going to settings
# 2. Ensure you are using the correct oc version
# 3. Change the values for the APPNAME, PROJECT and REPO

name: Master Branch

on:
  push:
    branches:
      - 'master'

env:
  PROJECT: petclinic
  APPNAME: pet2
  REPO: https://github.com/lstocchi/spring-petclinic.git

jobs:

  test:
    name: Build jar
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Maven Package
        run: mvn package -DskipTests
          
  build-deploy:
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.1.0
      with:
        version: '4.3'
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
      cmd: |
        oc project ${PROJECT} || oc new-project ${PROJECT}
        oc new-build java~${REPO} --name ${APPNAME}
        oc start-build ${APPNAME} --from-dir . --follow
        oc new-app ${APPNAME}:latest